### ISSUE TITLE
Lg

### ISSUE THREAD

**Issue by Cr1cker** [reprodev/LGTV-Firmware-Downgrade#2]

**Comment by reprodev** [comment]
Hi Cr1cker what's the issue you are currently having with this so I can take a look at it.

It would help if you could let me know the following information as below

- Type of Issue
- LG TV Model and Model Number
- WebOS and Firmware Version
- What you've tried already so we can see if it can be worked on

Reprodev

**Comment by reprodev** [comment]
Closing this ticket but please open a new one if you still need with the information above so I can look into it for you
